/*
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRealopValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(no.sintef.xtext.dsl.operator.realop.RealopPackage.eINSTANCE);
		return result;
	}
	
}
