/*
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.parser.antlr;

import com.google.inject.Inject;
import no.sintef.xtext.dsl.operator.parser.antlr.internal.InternalRealopParser;
import no.sintef.xtext.dsl.operator.services.RealopGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RealopParser extends AbstractAntlrParser {

	@Inject
	private RealopGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRealopParser createParser(XtextTokenStream stream) {
		return new InternalRealopParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Realop";
	}

	public RealopGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RealopGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
