/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator;

import no.sintef.xtext.dsl.operator.AbstractRealopRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RealopRuntimeModule extends AbstractRealopRuntimeModule {
}
