/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator;

import no.sintef.xtext.dsl.operator.RealopStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RealopStandaloneSetup extends RealopStandaloneSetupGenerated {
  public static void doSetup() {
    RealopStandaloneSetup _realopStandaloneSetup = new RealopStandaloneSetup();
    _realopStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
