/*
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.ui;

import com.google.inject.Injector;
import no.sintef.xtext.dsl.operator.ui.internal.OperatorActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RealopExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OperatorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OperatorActivator.getInstance().getInjector(OperatorActivator.NO_SINTEF_XTEXT_DSL_OPERATOR_REALOP);
	}
	
}
