/*
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class RealopUiModule extends AbstractRealopUiModule {
}
