/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.realop.impl;

import no.sintef.xtext.dsl.operator.realop.Logic;
import no.sintef.xtext.dsl.operator.realop.RealopPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Logic</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.impl.LogicImpl#isAnd <em>And</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.impl.LogicImpl#isOr <em>Or</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.impl.LogicImpl#isXor <em>Xor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LogicImpl extends MinimalEObjectImpl.Container implements Logic
{
  /**
   * The default value of the '{@link #isAnd() <em>And</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAnd()
   * @generated
   * @ordered
   */
  protected static final boolean AND_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isAnd() <em>And</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAnd()
   * @generated
   * @ordered
   */
  protected boolean and = AND_EDEFAULT;

  /**
   * The default value of the '{@link #isOr() <em>Or</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOr()
   * @generated
   * @ordered
   */
  protected static final boolean OR_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isOr() <em>Or</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOr()
   * @generated
   * @ordered
   */
  protected boolean or = OR_EDEFAULT;

  /**
   * The default value of the '{@link #isXor() <em>Xor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isXor()
   * @generated
   * @ordered
   */
  protected static final boolean XOR_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isXor() <em>Xor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isXor()
   * @generated
   * @ordered
   */
  protected boolean xor = XOR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LogicImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RealopPackage.Literals.LOGIC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isAnd()
  {
    return and;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAnd(boolean newAnd)
  {
    boolean oldAnd = and;
    and = newAnd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RealopPackage.LOGIC__AND, oldAnd, and));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isOr()
  {
    return or;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOr(boolean newOr)
  {
    boolean oldOr = or;
    or = newOr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RealopPackage.LOGIC__OR, oldOr, or));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isXor()
  {
    return xor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setXor(boolean newXor)
  {
    boolean oldXor = xor;
    xor = newXor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RealopPackage.LOGIC__XOR, oldXor, xor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RealopPackage.LOGIC__AND:
        return isAnd();
      case RealopPackage.LOGIC__OR:
        return isOr();
      case RealopPackage.LOGIC__XOR:
        return isXor();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RealopPackage.LOGIC__AND:
        setAnd((Boolean)newValue);
        return;
      case RealopPackage.LOGIC__OR:
        setOr((Boolean)newValue);
        return;
      case RealopPackage.LOGIC__XOR:
        setXor((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RealopPackage.LOGIC__AND:
        setAnd(AND_EDEFAULT);
        return;
      case RealopPackage.LOGIC__OR:
        setOr(OR_EDEFAULT);
        return;
      case RealopPackage.LOGIC__XOR:
        setXor(XOR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RealopPackage.LOGIC__AND:
        return and != AND_EDEFAULT;
      case RealopPackage.LOGIC__OR:
        return or != OR_EDEFAULT;
      case RealopPackage.LOGIC__XOR:
        return xor != XOR_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (and: ");
    result.append(and);
    result.append(", or: ");
    result.append(or);
    result.append(", xor: ");
    result.append(xor);
    result.append(')');
    return result.toString();
  }

} //LogicImpl
