/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.realop.impl;

import no.sintef.xtext.dsl.operator.realop.Expression;
import no.sintef.xtext.dsl.operator.realop.Operator;
import no.sintef.xtext.dsl.operator.realop.RealopPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operator</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.impl.OperatorImpl#getName <em>Name</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.impl.OperatorImpl#getExp_pre <em>Exp pre</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.impl.OperatorImpl#getExp_post <em>Exp post</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OperatorImpl extends MinimalEObjectImpl.Container implements Operator
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getExp_pre() <em>Exp pre</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExp_pre()
   * @generated
   * @ordered
   */
  protected Expression exp_pre;

  /**
   * The cached value of the '{@link #getExp_post() <em>Exp post</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExp_post()
   * @generated
   * @ordered
   */
  protected Expression exp_post;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RealopPackage.Literals.OPERATOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RealopPackage.OPERATOR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExp_pre()
  {
    return exp_pre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExp_pre(Expression newExp_pre, NotificationChain msgs)
  {
    Expression oldExp_pre = exp_pre;
    exp_pre = newExp_pre;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RealopPackage.OPERATOR__EXP_PRE, oldExp_pre, newExp_pre);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExp_pre(Expression newExp_pre)
  {
    if (newExp_pre != exp_pre)
    {
      NotificationChain msgs = null;
      if (exp_pre != null)
        msgs = ((InternalEObject)exp_pre).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RealopPackage.OPERATOR__EXP_PRE, null, msgs);
      if (newExp_pre != null)
        msgs = ((InternalEObject)newExp_pre).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RealopPackage.OPERATOR__EXP_PRE, null, msgs);
      msgs = basicSetExp_pre(newExp_pre, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RealopPackage.OPERATOR__EXP_PRE, newExp_pre, newExp_pre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExp_post()
  {
    return exp_post;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExp_post(Expression newExp_post, NotificationChain msgs)
  {
    Expression oldExp_post = exp_post;
    exp_post = newExp_post;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RealopPackage.OPERATOR__EXP_POST, oldExp_post, newExp_post);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExp_post(Expression newExp_post)
  {
    if (newExp_post != exp_post)
    {
      NotificationChain msgs = null;
      if (exp_post != null)
        msgs = ((InternalEObject)exp_post).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RealopPackage.OPERATOR__EXP_POST, null, msgs);
      if (newExp_post != null)
        msgs = ((InternalEObject)newExp_post).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RealopPackage.OPERATOR__EXP_POST, null, msgs);
      msgs = basicSetExp_post(newExp_post, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RealopPackage.OPERATOR__EXP_POST, newExp_post, newExp_post));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RealopPackage.OPERATOR__EXP_PRE:
        return basicSetExp_pre(null, msgs);
      case RealopPackage.OPERATOR__EXP_POST:
        return basicSetExp_post(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RealopPackage.OPERATOR__NAME:
        return getName();
      case RealopPackage.OPERATOR__EXP_PRE:
        return getExp_pre();
      case RealopPackage.OPERATOR__EXP_POST:
        return getExp_post();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RealopPackage.OPERATOR__NAME:
        setName((String)newValue);
        return;
      case RealopPackage.OPERATOR__EXP_PRE:
        setExp_pre((Expression)newValue);
        return;
      case RealopPackage.OPERATOR__EXP_POST:
        setExp_post((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RealopPackage.OPERATOR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RealopPackage.OPERATOR__EXP_PRE:
        setExp_pre((Expression)null);
        return;
      case RealopPackage.OPERATOR__EXP_POST:
        setExp_post((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RealopPackage.OPERATOR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RealopPackage.OPERATOR__EXP_PRE:
        return exp_pre != null;
      case RealopPackage.OPERATOR__EXP_POST:
        return exp_post != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //OperatorImpl
