/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.realop.impl;

import no.sintef.xtext.dsl.operator.realop.Predicate;
import no.sintef.xtext.dsl.operator.realop.RealopPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Predicate</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.impl.PredicateImpl#isNegate <em>Negate</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.impl.PredicateImpl#getPredicate <em>Predicate</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.impl.PredicateImpl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PredicateImpl extends MinimalEObjectImpl.Container implements Predicate
{
  /**
   * The default value of the '{@link #isNegate() <em>Negate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNegate()
   * @generated
   * @ordered
   */
  protected static final boolean NEGATE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isNegate() <em>Negate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNegate()
   * @generated
   * @ordered
   */
  protected boolean negate = NEGATE_EDEFAULT;

  /**
   * The default value of the '{@link #getPredicate() <em>Predicate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPredicate()
   * @generated
   * @ordered
   */
  protected static final String PREDICATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPredicate() <em>Predicate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPredicate()
   * @generated
   * @ordered
   */
  protected String predicate = PREDICATE_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PredicateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RealopPackage.Literals.PREDICATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isNegate()
  {
    return negate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNegate(boolean newNegate)
  {
    boolean oldNegate = negate;
    negate = newNegate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RealopPackage.PREDICATE__NEGATE, oldNegate, negate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPredicate()
  {
    return predicate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPredicate(String newPredicate)
  {
    String oldPredicate = predicate;
    predicate = newPredicate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RealopPackage.PREDICATE__PREDICATE, oldPredicate, predicate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RealopPackage.PREDICATE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RealopPackage.PREDICATE__NEGATE:
        return isNegate();
      case RealopPackage.PREDICATE__PREDICATE:
        return getPredicate();
      case RealopPackage.PREDICATE__NAME:
        return getName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RealopPackage.PREDICATE__NEGATE:
        setNegate((Boolean)newValue);
        return;
      case RealopPackage.PREDICATE__PREDICATE:
        setPredicate((String)newValue);
        return;
      case RealopPackage.PREDICATE__NAME:
        setName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RealopPackage.PREDICATE__NEGATE:
        setNegate(NEGATE_EDEFAULT);
        return;
      case RealopPackage.PREDICATE__PREDICATE:
        setPredicate(PREDICATE_EDEFAULT);
        return;
      case RealopPackage.PREDICATE__NAME:
        setName(NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RealopPackage.PREDICATE__NEGATE:
        return negate != NEGATE_EDEFAULT;
      case RealopPackage.PREDICATE__PREDICATE:
        return PREDICATE_EDEFAULT == null ? predicate != null : !PREDICATE_EDEFAULT.equals(predicate);
      case RealopPackage.PREDICATE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (negate: ");
    result.append(negate);
    result.append(", predicate: ");
    result.append(predicate);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //PredicateImpl
