/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.realop;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Expression#getLhs <em>Lhs</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Expression#getRhs <em>Rhs</em>}</li>
 * </ul>
 *
 * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lhs</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lhs</em>' containment reference.
   * @see #setLhs(Predicate)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getExpression_Lhs()
   * @model containment="true"
   * @generated
   */
  Predicate getLhs();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Expression#getLhs <em>Lhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lhs</em>' containment reference.
   * @see #getLhs()
   * @generated
   */
  void setLhs(Predicate value);

  /**
   * Returns the value of the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rhs</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rhs</em>' containment reference.
   * @see #setRhs(TerminalExpression)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getExpression_Rhs()
   * @model containment="true"
   * @generated
   */
  TerminalExpression getRhs();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Expression#getRhs <em>Rhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rhs</em>' containment reference.
   * @see #getRhs()
   * @generated
   */
  void setRhs(TerminalExpression value);

} // Expression
