/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.realop;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Operator#getName <em>Name</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Operator#getExp_pre <em>Exp pre</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Operator#getExp_post <em>Exp post</em>}</li>
 * </ul>
 *
 * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getOperator()
 * @model
 * @generated
 */
public interface Operator extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getOperator_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Operator#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Exp pre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp pre</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp pre</em>' containment reference.
   * @see #setExp_pre(Expression)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getOperator_Exp_pre()
   * @model containment="true"
   * @generated
   */
  Expression getExp_pre();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Operator#getExp_pre <em>Exp pre</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp pre</em>' containment reference.
   * @see #getExp_pre()
   * @generated
   */
  void setExp_pre(Expression value);

  /**
   * Returns the value of the '<em><b>Exp post</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp post</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp post</em>' containment reference.
   * @see #setExp_post(Expression)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getOperator_Exp_post()
   * @model containment="true"
   * @generated
   */
  Expression getExp_post();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Operator#getExp_post <em>Exp post</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp post</em>' containment reference.
   * @see #getExp_post()
   * @generated
   */
  void setExp_post(Expression value);

} // Operator
