/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.realop;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Predicate#isNegate <em>Negate</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Predicate#getPredicate <em>Predicate</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Predicate#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getPredicate()
 * @model
 * @generated
 */
public interface Predicate extends EObject
{
  /**
   * Returns the value of the '<em><b>Negate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Negate</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Negate</em>' attribute.
   * @see #setNegate(boolean)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getPredicate_Negate()
   * @model
   * @generated
   */
  boolean isNegate();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Predicate#isNegate <em>Negate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Negate</em>' attribute.
   * @see #isNegate()
   * @generated
   */
  void setNegate(boolean value);

  /**
   * Returns the value of the '<em><b>Predicate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Predicate</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' attribute.
   * @see #setPredicate(String)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getPredicate_Predicate()
   * @model
   * @generated
   */
  String getPredicate();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Predicate#getPredicate <em>Predicate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' attribute.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getPredicate_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Predicate#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Predicate
