/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.realop;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicates</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Predicates#isRealised <em>Realised</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Predicates#isPositive <em>Positive</em>}</li>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Predicates#isNegative <em>Negative</em>}</li>
 * </ul>
 *
 * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getPredicates()
 * @model
 * @generated
 */
public interface Predicates extends EObject
{
  /**
   * Returns the value of the '<em><b>Realised</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Realised</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Realised</em>' attribute.
   * @see #setRealised(boolean)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getPredicates_Realised()
   * @model
   * @generated
   */
  boolean isRealised();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Predicates#isRealised <em>Realised</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Realised</em>' attribute.
   * @see #isRealised()
   * @generated
   */
  void setRealised(boolean value);

  /**
   * Returns the value of the '<em><b>Positive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Positive</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Positive</em>' attribute.
   * @see #setPositive(boolean)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getPredicates_Positive()
   * @model
   * @generated
   */
  boolean isPositive();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Predicates#isPositive <em>Positive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Positive</em>' attribute.
   * @see #isPositive()
   * @generated
   */
  void setPositive(boolean value);

  /**
   * Returns the value of the '<em><b>Negative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Negative</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Negative</em>' attribute.
   * @see #setNegative(boolean)
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getPredicates_Negative()
   * @model
   * @generated
   */
  boolean isNegative();

  /**
   * Sets the value of the '{@link no.sintef.xtext.dsl.operator.realop.Predicates#isNegative <em>Negative</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Negative</em>' attribute.
   * @see #isNegative()
   * @generated
   */
  void setNegative(boolean value);

} // Predicates
