/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.realop;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Realop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link no.sintef.xtext.dsl.operator.realop.Realop#getOperator <em>Operator</em>}</li>
 * </ul>
 *
 * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getRealop()
 * @model
 * @generated
 */
public interface Realop extends EObject
{
  /**
   * Returns the value of the '<em><b>Operator</b></em>' containment reference list.
   * The list contents are of type {@link no.sintef.xtext.dsl.operator.realop.Operator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operator</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' containment reference list.
   * @see no.sintef.xtext.dsl.operator.realop.RealopPackage#getRealop_Operator()
   * @model containment="true"
   * @generated
   */
  EList<Operator> getOperator();

} // Realop
