/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.realop;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see no.sintef.xtext.dsl.operator.realop.RealopFactory
 * @model kind="package"
 * @generated
 */
public interface RealopPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "realop";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sintef.no/xtext/dsl/operator/Realop";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "realop";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RealopPackage eINSTANCE = no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl.init();

  /**
   * The meta object id for the '{@link no.sintef.xtext.dsl.operator.realop.impl.RealopImpl <em>Realop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.sintef.xtext.dsl.operator.realop.impl.RealopImpl
   * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getRealop()
   * @generated
   */
  int REALOP = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REALOP__OPERATOR = 0;

  /**
   * The number of structural features of the '<em>Realop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REALOP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link no.sintef.xtext.dsl.operator.realop.impl.OperatorImpl <em>Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.sintef.xtext.dsl.operator.realop.impl.OperatorImpl
   * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Exp pre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__EXP_PRE = 1;

  /**
   * The feature id for the '<em><b>Exp post</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__EXP_POST = 2;

  /**
   * The number of structural features of the '<em>Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link no.sintef.xtext.dsl.operator.realop.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.sintef.xtext.dsl.operator.realop.impl.ExpressionImpl
   * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 2;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__LHS = 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__RHS = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link no.sintef.xtext.dsl.operator.realop.impl.TerminalExpressionImpl <em>Terminal Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.sintef.xtext.dsl.operator.realop.impl.TerminalExpressionImpl
   * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getTerminalExpression()
   * @generated
   */
  int TERMINAL_EXPRESSION = 3;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINAL_EXPRESSION__OP = 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINAL_EXPRESSION__RHS = 1;

  /**
   * The number of structural features of the '<em>Terminal Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINAL_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link no.sintef.xtext.dsl.operator.realop.impl.LogicImpl <em>Logic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.sintef.xtext.dsl.operator.realop.impl.LogicImpl
   * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getLogic()
   * @generated
   */
  int LOGIC = 4;

  /**
   * The feature id for the '<em><b>And</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC__AND = 0;

  /**
   * The feature id for the '<em><b>Or</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC__OR = 1;

  /**
   * The feature id for the '<em><b>Xor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC__XOR = 2;

  /**
   * The number of structural features of the '<em>Logic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link no.sintef.xtext.dsl.operator.realop.impl.PredicateImpl <em>Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.sintef.xtext.dsl.operator.realop.impl.PredicateImpl
   * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getPredicate()
   * @generated
   */
  int PREDICATE = 5;

  /**
   * The feature id for the '<em><b>Negated</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__NEGATED = 0;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__PREDICATE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__NAME = 2;

  /**
   * The number of structural features of the '<em>Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link no.sintef.xtext.dsl.operator.realop.impl.PredicatesImpl <em>Predicates</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see no.sintef.xtext.dsl.operator.realop.impl.PredicatesImpl
   * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getPredicates()
   * @generated
   */
  int PREDICATES = 6;

  /**
   * The feature id for the '<em><b>Realised</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATES__REALISED = 0;

  /**
   * The feature id for the '<em><b>Positive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATES__POSITIVE = 1;

  /**
   * The feature id for the '<em><b>Negative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATES__NEGATIVE = 2;

  /**
   * The number of structural features of the '<em>Predicates</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATES_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link no.sintef.xtext.dsl.operator.realop.Realop <em>Realop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Realop</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Realop
   * @generated
   */
  EClass getRealop();

  /**
   * Returns the meta object for the containment reference list '{@link no.sintef.xtext.dsl.operator.realop.Realop#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operator</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Realop#getOperator()
   * @see #getRealop()
   * @generated
   */
  EReference getRealop_Operator();

  /**
   * Returns the meta object for class '{@link no.sintef.xtext.dsl.operator.realop.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operator</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Operator
   * @generated
   */
  EClass getOperator();

  /**
   * Returns the meta object for the attribute '{@link no.sintef.xtext.dsl.operator.realop.Operator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Operator#getName()
   * @see #getOperator()
   * @generated
   */
  EAttribute getOperator_Name();

  /**
   * Returns the meta object for the containment reference '{@link no.sintef.xtext.dsl.operator.realop.Operator#getExp_pre <em>Exp pre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp pre</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Operator#getExp_pre()
   * @see #getOperator()
   * @generated
   */
  EReference getOperator_Exp_pre();

  /**
   * Returns the meta object for the containment reference '{@link no.sintef.xtext.dsl.operator.realop.Operator#getExp_post <em>Exp post</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp post</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Operator#getExp_post()
   * @see #getOperator()
   * @generated
   */
  EReference getOperator_Exp_post();

  /**
   * Returns the meta object for class '{@link no.sintef.xtext.dsl.operator.realop.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link no.sintef.xtext.dsl.operator.realop.Expression#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Expression#getLhs()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link no.sintef.xtext.dsl.operator.realop.Expression#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Expression#getRhs()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Rhs();

  /**
   * Returns the meta object for class '{@link no.sintef.xtext.dsl.operator.realop.TerminalExpression <em>Terminal Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Terminal Expression</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.TerminalExpression
   * @generated
   */
  EClass getTerminalExpression();

  /**
   * Returns the meta object for the containment reference '{@link no.sintef.xtext.dsl.operator.realop.TerminalExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Op</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.TerminalExpression#getOp()
   * @see #getTerminalExpression()
   * @generated
   */
  EReference getTerminalExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link no.sintef.xtext.dsl.operator.realop.TerminalExpression#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.TerminalExpression#getRhs()
   * @see #getTerminalExpression()
   * @generated
   */
  EReference getTerminalExpression_Rhs();

  /**
   * Returns the meta object for class '{@link no.sintef.xtext.dsl.operator.realop.Logic <em>Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Logic
   * @generated
   */
  EClass getLogic();

  /**
   * Returns the meta object for the attribute '{@link no.sintef.xtext.dsl.operator.realop.Logic#isAnd <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>And</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Logic#isAnd()
   * @see #getLogic()
   * @generated
   */
  EAttribute getLogic_And();

  /**
   * Returns the meta object for the attribute '{@link no.sintef.xtext.dsl.operator.realop.Logic#isOr <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Or</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Logic#isOr()
   * @see #getLogic()
   * @generated
   */
  EAttribute getLogic_Or();

  /**
   * Returns the meta object for the attribute '{@link no.sintef.xtext.dsl.operator.realop.Logic#isXor <em>Xor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Xor</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Logic#isXor()
   * @see #getLogic()
   * @generated
   */
  EAttribute getLogic_Xor();

  /**
   * Returns the meta object for class '{@link no.sintef.xtext.dsl.operator.realop.Predicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Predicate
   * @generated
   */
  EClass getPredicate();

  /**
   * Returns the meta object for the attribute '{@link no.sintef.xtext.dsl.operator.realop.Predicate#isNegated <em>Negated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Negated</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Predicate#isNegated()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_Negated();

  /**
   * Returns the meta object for the containment reference '{@link no.sintef.xtext.dsl.operator.realop.Predicate#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Predicate#getPredicate()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_Predicate();

  /**
   * Returns the meta object for the attribute '{@link no.sintef.xtext.dsl.operator.realop.Predicate#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Predicate#getName()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_Name();

  /**
   * Returns the meta object for class '{@link no.sintef.xtext.dsl.operator.realop.Predicates <em>Predicates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicates</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Predicates
   * @generated
   */
  EClass getPredicates();

  /**
   * Returns the meta object for the attribute '{@link no.sintef.xtext.dsl.operator.realop.Predicates#isRealised <em>Realised</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Realised</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Predicates#isRealised()
   * @see #getPredicates()
   * @generated
   */
  EAttribute getPredicates_Realised();

  /**
   * Returns the meta object for the attribute '{@link no.sintef.xtext.dsl.operator.realop.Predicates#isPositive <em>Positive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Positive</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Predicates#isPositive()
   * @see #getPredicates()
   * @generated
   */
  EAttribute getPredicates_Positive();

  /**
   * Returns the meta object for the attribute '{@link no.sintef.xtext.dsl.operator.realop.Predicates#isNegative <em>Negative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Negative</em>'.
   * @see no.sintef.xtext.dsl.operator.realop.Predicates#isNegative()
   * @see #getPredicates()
   * @generated
   */
  EAttribute getPredicates_Negative();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RealopFactory getRealopFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link no.sintef.xtext.dsl.operator.realop.impl.RealopImpl <em>Realop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.sintef.xtext.dsl.operator.realop.impl.RealopImpl
     * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getRealop()
     * @generated
     */
    EClass REALOP = eINSTANCE.getRealop();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REALOP__OPERATOR = eINSTANCE.getRealop_Operator();

    /**
     * The meta object literal for the '{@link no.sintef.xtext.dsl.operator.realop.impl.OperatorImpl <em>Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.sintef.xtext.dsl.operator.realop.impl.OperatorImpl
     * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getOperator()
     * @generated
     */
    EClass OPERATOR = eINSTANCE.getOperator();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATOR__NAME = eINSTANCE.getOperator_Name();

    /**
     * The meta object literal for the '<em><b>Exp pre</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATOR__EXP_PRE = eINSTANCE.getOperator_Exp_pre();

    /**
     * The meta object literal for the '<em><b>Exp post</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATOR__EXP_POST = eINSTANCE.getOperator_Exp_post();

    /**
     * The meta object literal for the '{@link no.sintef.xtext.dsl.operator.realop.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.sintef.xtext.dsl.operator.realop.impl.ExpressionImpl
     * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__LHS = eINSTANCE.getExpression_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__RHS = eINSTANCE.getExpression_Rhs();

    /**
     * The meta object literal for the '{@link no.sintef.xtext.dsl.operator.realop.impl.TerminalExpressionImpl <em>Terminal Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.sintef.xtext.dsl.operator.realop.impl.TerminalExpressionImpl
     * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getTerminalExpression()
     * @generated
     */
    EClass TERMINAL_EXPRESSION = eINSTANCE.getTerminalExpression();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINAL_EXPRESSION__OP = eINSTANCE.getTerminalExpression_Op();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINAL_EXPRESSION__RHS = eINSTANCE.getTerminalExpression_Rhs();

    /**
     * The meta object literal for the '{@link no.sintef.xtext.dsl.operator.realop.impl.LogicImpl <em>Logic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.sintef.xtext.dsl.operator.realop.impl.LogicImpl
     * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getLogic()
     * @generated
     */
    EClass LOGIC = eINSTANCE.getLogic();

    /**
     * The meta object literal for the '<em><b>And</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGIC__AND = eINSTANCE.getLogic_And();

    /**
     * The meta object literal for the '<em><b>Or</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGIC__OR = eINSTANCE.getLogic_Or();

    /**
     * The meta object literal for the '<em><b>Xor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGIC__XOR = eINSTANCE.getLogic_Xor();

    /**
     * The meta object literal for the '{@link no.sintef.xtext.dsl.operator.realop.impl.PredicateImpl <em>Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.sintef.xtext.dsl.operator.realop.impl.PredicateImpl
     * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getPredicate()
     * @generated
     */
    EClass PREDICATE = eINSTANCE.getPredicate();

    /**
     * The meta object literal for the '<em><b>Negated</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__NEGATED = eINSTANCE.getPredicate_Negated();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__PREDICATE = eINSTANCE.getPredicate_Predicate();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__NAME = eINSTANCE.getPredicate_Name();

    /**
     * The meta object literal for the '{@link no.sintef.xtext.dsl.operator.realop.impl.PredicatesImpl <em>Predicates</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see no.sintef.xtext.dsl.operator.realop.impl.PredicatesImpl
     * @see no.sintef.xtext.dsl.operator.realop.impl.RealopPackageImpl#getPredicates()
     * @generated
     */
    EClass PREDICATES = eINSTANCE.getPredicates();

    /**
     * The meta object literal for the '<em><b>Realised</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATES__REALISED = eINSTANCE.getPredicates_Realised();

    /**
     * The meta object literal for the '<em><b>Positive</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATES__POSITIVE = eINSTANCE.getPredicates_Positive();

    /**
     * The meta object literal for the '<em><b>Negative</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATES__NEGATIVE = eINSTANCE.getPredicates_Negative();

  }

} //RealopPackage
