/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.tests;

import com.google.inject.Inject;
import no.sintef.xtext.dsl.operator.realop.Realop;
import no.sintef.xtext.dsl.operator.tests.RealopInjectorProvider;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(RealopInjectorProvider.class)
@SuppressWarnings("all")
public class RealopParsingTest {
  @Inject
  private ParseHelper<Realop> parseHelper;
  
  @Test
  public void testGrammar() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field negate is undefined for the type Predicate");
  }
}
