/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.ui;

import no.sintef.xtext.dsl.operator.ui.AbstractRealopUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RealopUiModule extends AbstractRealopUiModule {
  public RealopUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
