/*
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRealopScopeProvider extends DelegatingScopeProvider {
}
