/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.ui.contentassist;

import no.sintef.xtext.dsl.operator.ui.contentassist.AbstractRealopProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RealopProposalProvider extends AbstractRealopProposalProvider {
}
