/**
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator.validation;

import no.sintef.xtext.dsl.operator.validation.AbstractRealopValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RealopValidator extends AbstractRealopValidator {
}
