/*
 * generated by Xtext 2.9.2
 */
package no.sintef.xtext.dsl.operator


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RealopRuntimeModule extends AbstractRealopRuntimeModule {
}
